version: '3'
services:
    furikake:
      build: .
      container_name: furikake
      environment:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_REGION
        - AWS_DEFAULT_REGION
        - AWS_PROFILE
        - BACKLOG_API_KEY
        - TZ=Asia/Tokyo
      volumes:
        - $HOME/.aws:/root/.aws
        - .:/work
      working_dir: /work
      entrypoint:
        - furikake
      command: [ "monitor" ]
