version: '3'
services:
    furikake:
      image: ruby:latest
      build: .
      container_name: furikake
      environment:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_REGION
        - AWS_DEFAULT_REGION
        - AWS_PROFILE
      volumes:
        - $HOME/.aws:/root/.aws
        - .:/work
      working_dir: /work
      entrypoint:
        - furikake
      command:
        - help
